from welcome_page import WelcomePage
from directory_input import DirectoryInputPage
from performed_operations_input import PerformedOperationsInputPage
from pause_options_input import PauseOptionsInputPage
from quality_control_input import QualityControlInputPage
from white_matter_input import WhiteMatterInputPage
from lesion_load_input import LesionLoadCalculationInputPage