from welcome_page import WelcomePage
from directory_input import DirectoryInputPage
from running_operations import RunningOperationsPage
from white_matter_input import WhiteMatterInputPage
from lesion_load_input import LesionLoadCalculationInputPage
from settings_input import SettingsInput
from stores import rois
from utils import isValidPath